# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/repos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/repos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/repos/CMakeFiles /storage/emulated/0/repos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/repos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ignoreme

# Build rule for target.
ignoreme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ignoreme
.PHONY : ignoreme

# fast build rule for target.
ignoreme/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/build
.PHONY : ignoreme/fast

glad/glad.o: glad/glad.c.o
.PHONY : glad/glad.o

# target to build an object file
glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/glad/glad.c.o
.PHONY : glad/glad.c.o

glad/glad.i: glad/glad.c.i
.PHONY : glad/glad.i

# target to preprocess a source file
glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/glad/glad.c.i
.PHONY : glad/glad.c.i

glad/glad.s: glad/glad.c.s
.PHONY : glad/glad.s

# target to generate assembly for a file
glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/glad/glad.c.s
.PHONY : glad/glad.c.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_impl_opengl3.o: imgui/imgui_impl_opengl3.cpp.o
.PHONY : imgui/imgui_impl_opengl3.o

# target to build an object file
imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_opengl3.cpp.o
.PHONY : imgui/imgui_impl_opengl3.cpp.o

imgui/imgui_impl_opengl3.i: imgui/imgui_impl_opengl3.cpp.i
.PHONY : imgui/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_opengl3.cpp.i
.PHONY : imgui/imgui_impl_opengl3.cpp.i

imgui/imgui_impl_opengl3.s: imgui/imgui_impl_opengl3.cpp.s
.PHONY : imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_opengl3.cpp.s
.PHONY : imgui/imgui_impl_opengl3.cpp.s

imgui/imgui_impl_sdl.o: imgui/imgui_impl_sdl.cpp.o
.PHONY : imgui/imgui_impl_sdl.o

# target to build an object file
imgui/imgui_impl_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_sdl.cpp.o
.PHONY : imgui/imgui_impl_sdl.cpp.o

imgui/imgui_impl_sdl.i: imgui/imgui_impl_sdl.cpp.i
.PHONY : imgui/imgui_impl_sdl.i

# target to preprocess a source file
imgui/imgui_impl_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_sdl.cpp.i
.PHONY : imgui/imgui_impl_sdl.cpp.i

imgui/imgui_impl_sdl.s: imgui/imgui_impl_sdl.cpp.s
.PHONY : imgui/imgui_impl_sdl.s

# target to generate assembly for a file
imgui/imgui_impl_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_sdl.cpp.s
.PHONY : imgui/imgui_impl_sdl.cpp.s

imgui/imgui_impl_sdlrenderer.o: imgui/imgui_impl_sdlrenderer.cpp.o
.PHONY : imgui/imgui_impl_sdlrenderer.o

# target to build an object file
imgui/imgui_impl_sdlrenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_sdlrenderer.cpp.o
.PHONY : imgui/imgui_impl_sdlrenderer.cpp.o

imgui/imgui_impl_sdlrenderer.i: imgui/imgui_impl_sdlrenderer.cpp.i
.PHONY : imgui/imgui_impl_sdlrenderer.i

# target to preprocess a source file
imgui/imgui_impl_sdlrenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_sdlrenderer.cpp.i
.PHONY : imgui/imgui_impl_sdlrenderer.cpp.i

imgui/imgui_impl_sdlrenderer.s: imgui/imgui_impl_sdlrenderer.cpp.s
.PHONY : imgui/imgui_impl_sdlrenderer.s

# target to generate assembly for a file
imgui/imgui_impl_sdlrenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_impl_sdlrenderer.cpp.s
.PHONY : imgui/imgui_impl_sdlrenderer.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

imgui/misc/cpp/imgui_stdlib.o: imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : imgui/misc/cpp/imgui_stdlib.o

# target to build an object file
imgui/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : imgui/misc/cpp/imgui_stdlib.cpp.o

imgui/misc/cpp/imgui_stdlib.i: imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : imgui/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
imgui/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : imgui/misc/cpp/imgui_stdlib.cpp.i

imgui/misc/cpp/imgui_stdlib.s: imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : imgui/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
imgui/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : imgui/misc/cpp/imgui_stdlib.cpp.s

include/GUIDirectoryBrowser.o: include/GUIDirectoryBrowser.cpp.o
.PHONY : include/GUIDirectoryBrowser.o

# target to build an object file
include/GUIDirectoryBrowser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIDirectoryBrowser.cpp.o
.PHONY : include/GUIDirectoryBrowser.cpp.o

include/GUIDirectoryBrowser.i: include/GUIDirectoryBrowser.cpp.i
.PHONY : include/GUIDirectoryBrowser.i

# target to preprocess a source file
include/GUIDirectoryBrowser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIDirectoryBrowser.cpp.i
.PHONY : include/GUIDirectoryBrowser.cpp.i

include/GUIDirectoryBrowser.s: include/GUIDirectoryBrowser.cpp.s
.PHONY : include/GUIDirectoryBrowser.s

# target to generate assembly for a file
include/GUIDirectoryBrowser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIDirectoryBrowser.cpp.s
.PHONY : include/GUIDirectoryBrowser.cpp.s

include/GUIFileBrowser.o: include/GUIFileBrowser.cpp.o
.PHONY : include/GUIFileBrowser.o

# target to build an object file
include/GUIFileBrowser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIFileBrowser.cpp.o
.PHONY : include/GUIFileBrowser.cpp.o

include/GUIFileBrowser.i: include/GUIFileBrowser.cpp.i
.PHONY : include/GUIFileBrowser.i

# target to preprocess a source file
include/GUIFileBrowser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIFileBrowser.cpp.i
.PHONY : include/GUIFileBrowser.cpp.i

include/GUIFileBrowser.s: include/GUIFileBrowser.cpp.s
.PHONY : include/GUIFileBrowser.s

# target to generate assembly for a file
include/GUIFileBrowser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIFileBrowser.cpp.s
.PHONY : include/GUIFileBrowser.cpp.s

include/GUILauncher.o: include/GUILauncher.cpp.o
.PHONY : include/GUILauncher.o

# target to build an object file
include/GUILauncher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUILauncher.cpp.o
.PHONY : include/GUILauncher.cpp.o

include/GUILauncher.i: include/GUILauncher.cpp.i
.PHONY : include/GUILauncher.i

# target to preprocess a source file
include/GUILauncher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUILauncher.cpp.i
.PHONY : include/GUILauncher.cpp.i

include/GUILauncher.s: include/GUILauncher.cpp.s
.PHONY : include/GUILauncher.s

# target to generate assembly for a file
include/GUILauncher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUILauncher.cpp.s
.PHONY : include/GUILauncher.cpp.s

include/GUIMessageDlg.o: include/GUIMessageDlg.cpp.o
.PHONY : include/GUIMessageDlg.o

# target to build an object file
include/GUIMessageDlg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIMessageDlg.cpp.o
.PHONY : include/GUIMessageDlg.cpp.o

include/GUIMessageDlg.i: include/GUIMessageDlg.cpp.i
.PHONY : include/GUIMessageDlg.i

# target to preprocess a source file
include/GUIMessageDlg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIMessageDlg.cpp.i
.PHONY : include/GUIMessageDlg.cpp.i

include/GUIMessageDlg.s: include/GUIMessageDlg.cpp.s
.PHONY : include/GUIMessageDlg.s

# target to generate assembly for a file
include/GUIMessageDlg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIMessageDlg.cpp.s
.PHONY : include/GUIMessageDlg.cpp.s

include/GUIShaderEdit.o: include/GUIShaderEdit.cpp.o
.PHONY : include/GUIShaderEdit.o

# target to build an object file
include/GUIShaderEdit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIShaderEdit.cpp.o
.PHONY : include/GUIShaderEdit.cpp.o

include/GUIShaderEdit.i: include/GUIShaderEdit.cpp.i
.PHONY : include/GUIShaderEdit.i

# target to preprocess a source file
include/GUIShaderEdit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIShaderEdit.cpp.i
.PHONY : include/GUIShaderEdit.cpp.i

include/GUIShaderEdit.s: include/GUIShaderEdit.cpp.s
.PHONY : include/GUIShaderEdit.s

# target to generate assembly for a file
include/GUIShaderEdit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUIShaderEdit.cpp.s
.PHONY : include/GUIShaderEdit.cpp.s

include/GUITestbed.o: include/GUITestbed.cpp.o
.PHONY : include/GUITestbed.o

# target to build an object file
include/GUITestbed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUITestbed.cpp.o
.PHONY : include/GUITestbed.cpp.o

include/GUITestbed.i: include/GUITestbed.cpp.i
.PHONY : include/GUITestbed.i

# target to preprocess a source file
include/GUITestbed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUITestbed.cpp.i
.PHONY : include/GUITestbed.cpp.i

include/GUITestbed.s: include/GUITestbed.cpp.s
.PHONY : include/GUITestbed.s

# target to generate assembly for a file
include/GUITestbed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/GUITestbed.cpp.s
.PHONY : include/GUITestbed.cpp.s

include/glres.o: include/glres.cpp.o
.PHONY : include/glres.o

# target to build an object file
include/glres.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/glres.cpp.o
.PHONY : include/glres.cpp.o

include/glres.i: include/glres.cpp.i
.PHONY : include/glres.i

# target to preprocess a source file
include/glres.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/glres.cpp.i
.PHONY : include/glres.cpp.i

include/glres.s: include/glres.cpp.s
.PHONY : include/glres.s

# target to generate assembly for a file
include/glres.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/glres.cpp.s
.PHONY : include/glres.cpp.s

include/glshader.o: include/glshader.cpp.o
.PHONY : include/glshader.o

# target to build an object file
include/glshader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/glshader.cpp.o
.PHONY : include/glshader.cpp.o

include/glshader.i: include/glshader.cpp.i
.PHONY : include/glshader.i

# target to preprocess a source file
include/glshader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/glshader.cpp.i
.PHONY : include/glshader.cpp.i

include/glshader.s: include/glshader.cpp.s
.PHONY : include/glshader.s

# target to generate assembly for a file
include/glshader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/glshader.cpp.s
.PHONY : include/glshader.cpp.s

include/platform.o: include/platform.cpp.o
.PHONY : include/platform.o

# target to build an object file
include/platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/platform.cpp.o
.PHONY : include/platform.cpp.o

include/platform.i: include/platform.cpp.i
.PHONY : include/platform.i

# target to preprocess a source file
include/platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/platform.cpp.i
.PHONY : include/platform.cpp.i

include/platform.s: include/platform.cpp.s
.PHONY : include/platform.s

# target to generate assembly for a file
include/platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/include/platform.cpp.s
.PHONY : include/platform.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/main.cpp.s
.PHONY : main.cpp.s

src/triangle_renderer.o: src/triangle_renderer.cpp.o
.PHONY : src/triangle_renderer.o

# target to build an object file
src/triangle_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/src/triangle_renderer.cpp.o
.PHONY : src/triangle_renderer.cpp.o

src/triangle_renderer.i: src/triangle_renderer.cpp.i
.PHONY : src/triangle_renderer.i

# target to preprocess a source file
src/triangle_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/src/triangle_renderer.cpp.i
.PHONY : src/triangle_renderer.cpp.i

src/triangle_renderer.s: src/triangle_renderer.cpp.s
.PHONY : src/triangle_renderer.s

# target to generate assembly for a file
src/triangle_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignoreme.dir/build.make CMakeFiles/ignoreme.dir/src/triangle_renderer.cpp.s
.PHONY : src/triangle_renderer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ignoreme"
	@echo "... glad/glad.o"
	@echo "... glad/glad.i"
	@echo "... glad/glad.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_impl_opengl3.o"
	@echo "... imgui/imgui_impl_opengl3.i"
	@echo "... imgui/imgui_impl_opengl3.s"
	@echo "... imgui/imgui_impl_sdl.o"
	@echo "... imgui/imgui_impl_sdl.i"
	@echo "... imgui/imgui_impl_sdl.s"
	@echo "... imgui/imgui_impl_sdlrenderer.o"
	@echo "... imgui/imgui_impl_sdlrenderer.i"
	@echo "... imgui/imgui_impl_sdlrenderer.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... imgui/misc/cpp/imgui_stdlib.o"
	@echo "... imgui/misc/cpp/imgui_stdlib.i"
	@echo "... imgui/misc/cpp/imgui_stdlib.s"
	@echo "... include/GUIDirectoryBrowser.o"
	@echo "... include/GUIDirectoryBrowser.i"
	@echo "... include/GUIDirectoryBrowser.s"
	@echo "... include/GUIFileBrowser.o"
	@echo "... include/GUIFileBrowser.i"
	@echo "... include/GUIFileBrowser.s"
	@echo "... include/GUILauncher.o"
	@echo "... include/GUILauncher.i"
	@echo "... include/GUILauncher.s"
	@echo "... include/GUIMessageDlg.o"
	@echo "... include/GUIMessageDlg.i"
	@echo "... include/GUIMessageDlg.s"
	@echo "... include/GUIShaderEdit.o"
	@echo "... include/GUIShaderEdit.i"
	@echo "... include/GUIShaderEdit.s"
	@echo "... include/GUITestbed.o"
	@echo "... include/GUITestbed.i"
	@echo "... include/GUITestbed.s"
	@echo "... include/glres.o"
	@echo "... include/glres.i"
	@echo "... include/glres.s"
	@echo "... include/glshader.o"
	@echo "... include/glshader.i"
	@echo "... include/glshader.s"
	@echo "... include/platform.o"
	@echo "... include/platform.i"
	@echo "... include/platform.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/triangle_renderer.o"
	@echo "... src/triangle_renderer.i"
	@echo "... src/triangle_renderer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

